import React, { useState } from 'react'
import { FormField, RenderCards } from '../Components'
import { animate } from '../assets'

const Homepage = () => {
    const [loading,setLoading]=useState(false)
    const [allPosts,setAllPosts]=useState(null)
    const[searchText,setSearchText]=useState('')
  return (
    <section>
      <div className='py-6 px-2'>
        <h1 className='py-4 px-4 text-4xl font-bold'>The Community Showcase</h1>
        <p className='py-4 px-6'>Browse through a collection of imaginative and visually stunning images generated by DALL-E AI</p>
      </div>
      <div className='mt-16'>
        <FormField />
      </div>
      <div className='px-6'>
            {loading ? <img src={animate} alt='loading' /> : 
            <>
            {searchText &&(
                <h2>Showing Results for <span className='font-bold'> {searchText} :</span></h2>
            )}
            </>}
      </div>
      <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>
            {searchText?(<>
                <RenderCards 
                data={[]}
                title="No Search Results Found!Try Again..."
                />
            </>):
            (<>
            <RenderCards 
            data={[]}
            title='No Posts Found!'
            />
            </>)}
      </div>
    </section>
  )
}

export default Homepage
